### ISSUE TITLE
Project isn't written in Rust using a functional style

### ISSUE THREAD

**Issue by SkyVault** [dakriy/Rosario-ROV#23]
Sorry man but this code is full of bugs because it isn't purly functional, c++ is a bug and will make your rover die underwater. I recommend either rewritting the whole thing in Rust, or using a good language like Lisp

**Comment by dakriy** [comment]
I am not super familiar with Rust, so I'll let you look into this. I do like having the power of C++ though. Especially things like reinterpret_cast, because that memory is whatever I say it is! Even though I can shoot myself in the foot...

**Comment by SkyVault** [comment]
I messing with you bro, rust is a meme, programming is a meme. lets all just program in python

**Comment by dakriy** [comment]
Python master race, except for this was written in python... just python wasn't fast enough, so I'm moving to C++
